import {useState,useRef,useEffect} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {Menu,Search,Bell,ChevronDown,User,Settings,LogOut} from 'lucide-react'
import {useAuth} from '../../context/AuthContext.jsx'
import AdminBreadcrumbs from './AdminBreadcrumbs.jsx'
export default function AdminTopbar({onMenuOpen}){
  const {user,logout}=useAuth();const navigate=useNavigate();const [menuOpen,setMenuOpen]=useState(false);const menuRef=useRef(null)
  useEffect(()=>{const h=e=>{if(menuRef.current&&!menuRef.current.contains(e.target))setMenuOpen(false)};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h)},[])
  const handleLogout=async()=>{await logout();navigate('/login')}
  return(<header className="sticky top-0 z-20 border-b border-forest/8 bg-cream/95 backdrop-blur-sm"><div className="flex items-center gap-3 px-4 sm:px-6 py-3"><button type="button" onClick={onMenuOpen} className="lg:hidden rounded-lg p-2 text-forest/70 hover:bg-forest/5" aria-label="Open menu"><Menu size={20}/></button><div className="hidden sm:block flex-1 min-w-0"><AdminBreadcrumbs/></div><div className="flex-1 sm:flex-none sm:w-56 lg:w-64 relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-forest/35"/><input type="search" placeholder="Search admin…" className="w-full rounded-xl border border-forest/12 bg-cream-soft py-2 pl-9 pr-3 text-sm focus:outline-none focus:ring-2 focus:ring-olive/40" aria-label="Global search"/></div><button type="button" className="relative rounded-lg p-2 text-forest/60 hover:bg-forest/5" aria-label="Notifications"><Bell size={18}/><span className="absolute top-1.5 right-1.5 h-1.5 w-1.5 rounded-full bg-olive"/></button><div className="relative" ref={menuRef}><button type="button" onClick={()=>setMenuOpen(v=>!v)} className="flex items-center gap-2 rounded-xl px-2 py-1.5 hover:bg-forest/5" aria-expanded={menuOpen}><div className="flex h-8 w-8 items-center justify-center rounded-full bg-forest text-cream text-xs font-semibold">{(user?.name||'A').charAt(0)}</div><span className="hidden md:block text-sm font-medium text-forest max-w-[120px] truncate">{user?.name||'Admin'}</span><ChevronDown size={14} className="hidden md:block text-forest/40"/></button>{menuOpen&&(<div className="absolute right-0 mt-1.5 w-48 rounded-xl border border-forest/10 bg-cream-soft shadow-lg py-1 z-50"><Link to="/admin/profile" onClick={()=>setMenuOpen(false)} className="flex items-center gap-2 px-3 py-2 text-sm text-forest hover:bg-forest/5"><User size={15}/> Profile</Link><Link to="/admin/settings" onClick={()=>setMenuOpen(false)} className="flex items-center gap-2 px-3 py-2 text-sm text-forest hover:bg-forest/5"><Settings size={15}/> Settings</Link><button type="button" onClick={handleLogout} className="flex w-full items-center gap-2 px-3 py-2 text-sm text-forest hover:bg-forest/5"><LogOut size={15}/> Logout</button></div>)}</div></div><div className="sm:hidden px-4 pb-2"><AdminBreadcrumbs/></div></header>)
}
