import {useState} from 'react'
import {Search,SlidersHorizontal} from 'lucide-react'
import AdminModal from './AdminModal.jsx'
export default function SearchFilterBar({search,onSearch,placeholder='Search…',filters=[],activeFilters={},onFilterChange,onClear}){
  const [open,setOpen]=useState(false)
  const count=Object.values(activeFilters).filter(v=>v&&v!=='all').length
  const controls=<div className="flex flex-wrap gap-2">{filters.map(f=><label key={f.key} className="flex flex-col gap-1 text-xs text-forest/60"><span className="font-medium">{f.label}</span><select value={activeFilters[f.key]||'all'} onChange={e=>onFilterChange?.(f.key,e.target.value)} className="rounded-xl border border-forest/15 bg-cream-soft px-3 py-2 text-sm text-forest focus:outline-none focus:ring-2 focus:ring-olive/40"><option value="all">All</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>)}</div>
  return(<div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="relative flex-1 max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-forest/40"/><input type="search" value={search} onChange={e=>onSearch?.(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-forest/15 bg-cream-soft py-2.5 pl-9 pr-3 text-sm focus:outline-none focus:ring-2 focus:ring-olive/40" aria-label="Search"/></div>{filters.length>0&&(<><div className="hidden md:flex items-end gap-3">{controls}{count>0&&<button type="button" onClick={onClear} className="mb-0.5 text-xs font-medium text-olive hover:underline">Clear all</button>}</div><button type="button" onClick={()=>setOpen(true)} className="md:hidden inline-flex items-center gap-2 rounded-xl border border-forest/15 px-3 py-2.5 text-sm font-medium text-forest"><SlidersHorizontal size={16}/>Filters{count>0&&<span className="rounded-full bg-olive text-cream text-[10px] font-bold px-1.5">{count}</span>}</button><AdminModal open={open} title="Filters" onClose={()=>setOpen(false)} size="sm"><div className="space-y-4">{controls}<div className="flex gap-2 pt-2"><button type="button" onClick={()=>{onClear?.();setOpen(false)}} className="flex-1 rounded-xl border border-forest/15 py-2.5 text-sm">Clear all</button><button type="button" onClick={()=>setOpen(false)} className="flex-1 rounded-xl bg-forest py-2.5 text-sm text-cream">Apply</button></div></div></AdminModal></>)}</div>)
}
